# This is a basic workflow that is manually triggered

name: Files Sync to AWS S3 Bucket
on:
  push:
    branches: ['feature/json-files']

  workflow_dispatch:

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.8' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
      - run: python --version
      - name: Test
        run: echo "start"
      - name: Branch name
        run: |
          echo running on branch ${GITHUB_REF##*/}
          echo $GITHUB_REPOSITORY
          echo Reference Branch $GITHUB_REF
          
  load_files_to_s3:
    #if: contains(github.ref, 'feature') || github.ref == 'develop'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Authenticate with AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Upload files in `aws/s3/`
        run: >
          aws s3 sync ./aws/s3/  s3://hem-landing/inbound/