on:  
  #push:
  pull_request:
    branches:
      - main

# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Test
        run: echo "start"
      - name: Branch name
        run: |
          echo running on branch ${GITHUB_REF##*/}
          echo $GITHUB_REPOSITORY
          echo Reference Branch $GITHUB_REF
          echo Head Reference Branch $GITHUB_HEAD_REF
          echo Base Branch $GITHUB_BASE_REF
          terget_branch=$GITHUB_BASE_REF
          source_branch=$GITHUB_HEAD_REF
          echo target branch $terget_branch
          echo source branch $source_branch

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      