####
name: Local files load to AWS S3 bucket

on:
  push:
    branches:
      - feature/json-files
      - dev01
    paths:
      - aws/s3/**

jobs:
  # For any given push event only one of these jobs will run, loading files to test, dev or prod
  # depending on the branch name.

  load_files_to_s3:
    # Including the branch name in the job name will help us track what's going on
    name: Load files to S3 from ${{ github.ref }}

    #if: contains(github.ref, 'feature') || github.ref == 'develop'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Authenticate with AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Upload files in `aws/s3/`
        run: >
          aws s3 sync ./aws/s3/  s3://hem-landing/inbound/